### ISSUE TITLE
disabling autolink doesn't work

### ISSUE THREAD

**Issue by stbuehler** [isso-comments/isso#557] opened 2019-07-08 11:16 UTC
Even after disabling `autolink` I get call kind of crap "linkified" (like `ld.so` to `<a href="http://ld.so" rel="nofollow noopener">ld.so</a>` or `/usr/lib/x86_64-linux-gnu/libc/memcpy-preload.so` to `/usr/lib/x86_64-linux-gnu/libc/<a href="http://memcpy-preload.so" rel="nofollow noopener">memcpy-preload.so</a>`).

Imho the `Sanitizer` shouldn't make new links, i.e. start `set_links` with `if new: return None`.

Opinions?

**Comment by ix5** [comment] 2021-12-31 22:56
Duplicate of https://github.com/posativ/isso/issues/751

**Comment by ix5** [comment] 2022-01-05 20:30
On a second glance, this is a different issue entirely. Reopening.

**Closed** 2024-03-10 23:55 UTC
Labels: server, needs-contributor, bug
